### ISSUE TITLE
Diffenator report Italics

### ISSUE THREAD

**Issue by vv-monsalve** [originaltype/kufam#16] opened 2021-01-21 23:25 UTC
These are the main differences reported by Diffenator. Please review all of them and ensure everything is working as expected.

Black Italic
![glyphs_modified](https://user-images.githubusercontent.com/48698976/105424772-fc2fed00-5c15-11eb-9006-6c28599f1756.gif)

Bold Italic
![glyphs_modified](https://user-images.githubusercontent.com/48698976/105425235-f5ee4080-5c16-11eb-91b9-f6712b3f5c10.gif)

SemiBold Italic
![glyphs_modified](https://user-images.githubusercontent.com/48698976/105425362-364dbe80-5c17-11eb-9573-a3dbb5a329fe.gif)

**Comment by vv-monsalve** [comment] 2021-01-21 23:26
![kerns_new](https://user-images.githubusercontent.com/48698976/105424888-36998a00-5c16-11eb-91ef-fa0a7e4259f1.gif)

**Comment by vv-monsalve** [comment] 2021-01-21 23:42
Although this was expected, please ensure there are all of the desired glyphs, 890 are reported as new.

![glyphs_new](https://user-images.githubusercontent.com/48698976/105425938-3c906a80-5c18-11eb-8d1c-cce14e8824a0.gif)

**Comment by arturschmal** [comment] 2021-01-27 15:27
@vv-monsalve Apart from the merging of the Arabic set into the italic source file, I can not explain the other differences as as nothing in the source files that affects this has been touched. Quite some of the characters reported seem to be the characters that have nested components. Could it be that the un-nesting in `build.sh` causes positional shifts?

**Comment by vv-monsalve** [comment] 2021-01-27 21:47
> Could it be that the un-nesting in `build.sh` causes positional shifts?

If after inspecting the source file it's confirmed nothing else has changed, then the two facts could be related.

It would be needed to run the `build.sh` without the `-f` flag to confirm.

**Comment by arturschmal** [comment] 2021-01-28 12:39
I compared source files from `master` with source files in `decompose-nested-transformed-components` with [MergeGlyphs](https://glyphsapp.com/tools/mergeglyphs) and it shows only the changes that are known to me. So apart from outline and kerning issues that I fixed the source files are identical.

I ran `build.sh` without the `-f flag `and then ran `gftools qa -f Kufam-BlackItalic.ttf -gfb -a -o qa`.
There's still quite some characters indicated as different, but the shifting of the nested components _before_ and _after_ is not there anymore. So `-f` does seem to affect component positioning.

**Comment by simoncozens** [comment] 2021-01-29 16:31
If there is a difference being caused by the `-f` flag, that would be a bug in `ufo2ft`. I'm happy to investigate but would need a bit more information.

If we can produce a small test case (just delete all irrelevant glyphs from the .glyphs file to leave one or two affected glyphs and the components they use), that would be helpful for debugging.

**Comment by vv-monsalve** [comment] 2021-01-29 20:51
Thanks, Simon. I'm attaching a file with a few glyphs. 
[Kufam_few-glyphs.zip](https://github.com/originaltype/kufam/files/5896253/Kufam_few-glyphs.zip)

**Comment by simoncozens** [comment] 2021-02-01 15:19
I can't see a difference. :-/

I had to delete a few more glyphs to make the fonts compile (missing components, deleted glyphs referenced in features features, etc.) My version attached.

```
$ fontmake -g Kufam_few-glyphs.glyphs -o ttf; mv master_ttf/Kufam-BlackItalic.ttf master_ttf/Kufam-BlackItalic-NonFlat.ttf
$ fontmake -f -g Kufam_few-glyphs.glyphs -o ttf; mv master_ttf/Kufam-BlackItalic.ttf master_ttf/Kufam-BlackItalic-Flat.ttf
$ shape shape master_ttf/Kufam-BlackItalic-Flat.ttf 'Ẫ'
[uni1EAA=0+736]
```
![shape](https://user-images.githubusercontent.com/106728/106477980-a7effd00-64a0-11eb-9e91-460912518779.png)
```
$ shape master_ttf/Kufam-BlackItalic-NonFlat.ttf 'Ẫ'
[uni1EAA=0+736]
```
![shape](https://user-images.githubusercontent.com/106728/106478056-bb9b6380-64a0-11eb-89fa-9cc90acf7855.png)
[Kufam_few-glyphs-SC.zip](https://github.com/originaltype/kufam/files/5904748/Kufam_few-glyphs-SC.zip)

**Comment by arturschmal** [comment] 2021-02-01 22:27
Hi Simon, thanks for doing this test. There is a slight vertical shift visible of the accents. You can see that in the flat version the accent has shifted down, closer towards the cap height.

**Comment by simoncozens** [comment] 2021-02-01 22:42
Yes, I see it now! Thanks! (Not a designer...)

Will investigate what’s happening. It’s obviously some ufo2ft thing.

**Comment by simoncozens** [comment] 2021-02-02 17:05
OK, this is actually fixed in the ufo2ft master repository, but no releases have been made yet. If you want to run bleeding-edge ufo2ft, then add this to your requirements file:

```
git+https://github.com/googlefonts/ufo2ft
```

Also run `pip3 install -U git+https://github.com/googlefonts/ufo2ft` to use the latest version on your local computer.

**Comment by vv-monsalve** [comment] 2021-02-02 17:11
Thanks! I'll try it and let you know

**Comment by vv-monsalve** [comment] 2021-02-02 23:54
I've pulled the latest files on the repo at commit  57906861db6a36077d18d0e3d3a07745bf4304fe, installed the latest version of `ufo2ft`, created new fonts and performed new checks. 
These are the new Diffenator reports for modified glyphs. For better comparison, here are the same images as in the [previous comment](https://github.com/originaltype/kufam/issues/16#issue-791565499)

**Black Italic**
![glyphs_modified](https://user-images.githubusercontent.com/48698976/106677296-8701d780-6586-11eb-9ba0-cac72e9e2805.gif)

**Bold Italic**
![glyphs_modified](https://user-images.githubusercontent.com/48698976/106677347-9e40c500-6586-11eb-9338-bdf09bfe96e5.gif)

**SemiBold Italic**
![glyphs_modified](https://user-images.githubusercontent.com/48698976/106677555-ea8c0500-6586-11eb-85f8-4a18b99e829b.gif)

Despite they are reported as modified (probably for the flattened components) I don't see any difference now on them, so I would say the `-f` flag is working.

There are other changes reported but regarding other things, like me base glyphs in the GDEF, so I'll report them in other Issues or comments.

Also, I'm attaching here the complete Diffenator report folder so that @arturschmal can inspect it in detail.

[qaKufam-Diffenator4.zip](https://github.com/originaltype/kufam/files/5915131/qaKufam-Diffenator4.zip)

**Comment by vv-monsalve** [comment] 2021-03-16 00:26
Hi @arturschmal, this is the Diffenator report after pulling the latest files in the repo at commit d7d87539f3aaf38cbaada34e978e3802b355689e

**Black Italic**
![glyphs_modified](https://user-images.githubusercontent.com/48698976/111237928-0e9a2780-85c4-11eb-9c98-938e4788b62c.gif)

**Bold Italic**
![glyphs_modified](https://user-images.githubusercontent.com/48698976/111237975-25d91500-85c4-11eb-9e57-00ddc4089789.gif)

**SemiBold**
![glyphs_modified](https://user-images.githubusercontent.com/48698976/111238035-40ab8980-85c4-11eb-858f-eff21db67d7e.gif)

**Closed as completed** 2021-05-12 08:37 UTC
